notifications:
    email: false
sudo: required

services:
    - docker

before_install:
    # Create .splunkrc file with default credentials
    - echo host=localhost >> $HOME/.splunkrc
    - echo username=admin >> $HOME/.splunkrc
    - echo password=changeme >> $HOME/.splunkrc
    # Set SPLUNK_HOME
    - export SPLUNK_HOME="/opt/splunk"
    # Pull docker image
    - docker pull adamryman/splunk-travis-ci:$SPLUNK_VERSION
    # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
    - sudo iptables -N DOCKER || true
    # Start Docker container
    - docker run -p 127.0.0.1:8089:8089 -d adamryman/splunk-travis-ci:$SPLUNK_VERSION;
    # curl Splunk until it returns valid data indicating it has been setup, try 20 times maximum
    - i="0";
      while [ $i -lt 20 ];
      do
        if curl -sk https://localhost:8089/services/server/info 1>/dev/null $2>1;  then
            break;
        fi;
        echo $i
        sleep 1;
        i=$[$i+1];
      done;

env:
    - SPLUNK_VERSION=6.2.5

language: csharp
solution: splunk-sdk-csharp-pcl.sln

mono:
  - latest

install:
  - nuget restore splunk-sdk-csharp-pcl.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

berfore_script: python setup.py build dist

script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MyPoject.Tests/bin/Release/MyProject.Tests.dll